#!/usr/bin/env python3
"""Fill missing translations in batch_level3_01.json."""
import json, sys, os
os.environ["PYTHONIOENCODING"] = "utf-8"
sys.stdout.reconfigure(encoding='utf-8')

with open('C:/Projects/OrwellRU/translated/batch_level3_01.json', 'r', encoding='utf-8') as f:
    batch = json.load(f)

# Translations for the 18 remaining strings (exact keys from batch)
fixes = {}

fixes['I am a veteran of the army of The Nation. My career was promising. I served for six years, was in charge of my own squad, and was a well respected combat engineer. I was dishonorably discharged in 2011, shortly after I went AWOL because of personal issues. I was sent back to The Nation as "deserter", and flushed down the toilet of life by the administration of the army, the Government, and their "Safety Bill". Since then I have been working in low-wage jobs, live in a crappy apartment in the industrial quarters, and can hardly afford daycare for my son.\r\n \r\nAfter many years, I now realize that the "causes" I was fighting for in the army were an illusion. I don\'t want my son to grow up in a country that doesn\'t respect its own people. They have not only flushed me down the drain, but the whole country. This government sucked up all of my vitality, just to spit me out again. All I am left with is anger, and a huge urge to keep my son safe from all this bullshit.\r'] = 'Я ветеран армии Нации. Карьера складывалась многообещающе. Шесть лет службы, командовал собственным отделением, был уважаемым военным инженером. В 2011 году меня с позором уволили после самовольной отлучки из-за личных проблем. Меня отправили обратно в Нацию как «дезертира» и спустили в унитаз жизни — армейское руководство, правительство и их «Закон о безопасности». С тех пор я перебиваюсь низкооплачиваемой работой, живу в дерьмовой квартире в промзоне и едва могу позволить себе детский сад для сына.\r\n \r\nСпустя годы я осознал, что «идеалы», за которые я воевал в армии, были иллюзией. Не хочу, чтобы мой сын рос в стране, которая не уважает собственный народ. Они спустили в канализацию не только меня, но и всю страну. Это правительство высосало из меня все силы, чтобы потом выплюнуть. Всё, что у меня осталось — злость и огромное желание уберечь сына от этого дерьма.\r'

fixes['By the way, Uncle Simos wanted to invite <link="data_oleg_neighborraban"><color=#5A5A5A>Oleg Bakay. Just because his family lives next door, doesn\'t mean we have to show hospitality to followers of the Kassart regime.</color></link> It\'s too much of a risk.\r'] = 'Кстати, дядя Симос хотел пригласить <link="data_oleg_neighborraban"><color=#5A5A5A>Олега Бакая. Но то, что его семья живёт по соседству, не значит, что мы должны оказывать гостеприимство сторонникам режима Кассарта.</color></link> Слишком большой риск.\r'

fixes["I am starting to doubt whether TPV represents what I stand for. We sell ourselves as a blog for the Pargesian people, defending their rights and protecting their freedom. As part of that, it is our duty to criticize the Pargesian government, and the military is a prime target. However, I never signed up to be labeled as a criminal. We don't threaten people, we don't kidnap people, and we CERTAINLY do not kill people!!\r"] = "Я начинаю сомневаться, что TPV отстаивает мои ценности. Мы позиционируем себя как блог паргесского народа, защищающий его права и свободы. И в рамках этого наш долг — критиковать правительство Паргеса, а военные — главная мишень. Однако я не подписывался на ярлык преступника. Мы не угрожаем людям, не похищаем людей и уж ТОЧНО не убиваем!!\r"

fixes['@PeoplesVoice Raban, we stand by you in these difficult times! The people of Parges need you more than ever and we will support you in your fight against #NationalLiars.\r'] = '@PeoplesVoice Рабан, мы с тобой в эти трудные времена! Народ Паргеса нуждается в тебе больше, чем когда-либо, и мы поддержим тебя в борьбе с #НациональнымиЛжецами.\r'

fixes['Recorded call indicates direct involvement of blog "The People\'s Voice" in the disappearance of <link="data_bayte_pargesianofficer"><color=#575756>Pargesian army officer Oleg Bakay</color></link>.\r'] = 'Записанный звонок указывает на причастность блога \u00abГолос Народа\u00bb к исчезновению <link="data_bayte_pargesianofficer"><color=#575756>офицера паргесской армии Олега Бакая</color></link>.\r'

fixes["We look genuinely happy. The perfect couple, finally moving in together. Life was simply wonderful, and it seemed as if it couldn't get any better. Was it true? \r"] = "Мы выглядим по-настоящему счастливыми. Идеальная пара, наконец-то переезжаем вместе. Жизнь была прекрасна, казалось, лучше и быть не может. Было ли это правдой? \r"

fixes['I am a Pargesian refugee, and crossed the border to The Nation about 9 months ago. I decided to escape the war and flee with my three children after my husband was shot by a sniper.\r\n \r\nThe journey was long and arduous, but we managed to get to The Nation in good health. Unfortunately, my daughter Darha has gone through a huge change since then. She used to be a very lively child. She really loved her Dad, and she misses him a lot. She has not said a word since we left our home. She will neither speak to me, nor to any of her siblings, or anyone else that I know of. I am really worried, and am desperately searching for help. \r'] = 'Я паргесская беженка, пересекла границу Нации около 9 месяцев назад. Я решила бежать от войны с тремя детьми после того, как моего мужа застрелил снайпер.\r\n \r\nПуть был долгим и тяжёлым, но мы добрались до Нации в добром здравии. К сожалению, моя дочь Дарха с тех пор сильно изменилась. Раньше она была очень живым ребёнком. Она очень любила папу и сильно по нему скучает. Она не произнесла ни слова с тех пор, как мы покинули дом. Она не разговаривает ни со мной, ни с братьями и сёстрами, ни с кем-либо ещё. Я очень волнуюсь и отчаянно ищу помощь. \r'

fixes['Hello Molly.\r\nInsults aside, I think it is quite typical of ex-soldiers to feel that self-help and psychotherapy shows weakness. I find it quite interesting that despite your doubts and prejudices, you chose to reach out to me. This is no small feat, in fact, it shows that you are determined to face your issues, and better yourself. No matter how difficult that may be. You are on the road to healing.\r\n \r\nThis feeling of loss, this overwhelming tide of emotions that you are experiencing, it sounds like you are suffering from PTSD. Post-Traumatic Stress Syndrome is a common condition that many former ex-soldiers suffer from after experiencing a great deal of trauma during war. The good news is that with counseling, the symptoms of PTSD can be treated. How about I offer you some private sessions, free of charge? In exchange, I would like to publish your story (anonymously of course), on my blog. Female soldiers are so rarely spoken about, and I feel that your story in particular would be extremely valuable to other former servicewomen who feel they cannot speak up.\r'] = 'Здравствуйте, Молли.\r\nОскорбления в сторону, но мне кажется, для бывших военных характерно считать, что самопомощь и психотерапия — проявление слабости. И мне интересно, что несмотря на все сомнения и предубеждения, вы решились обратиться ко мне. Это серьёзный шаг, который говорит о вашей решимости разобраться с проблемами и стать лучше. Какими бы трудными они ни были. Вы на пути к исцелению.\r\n \r\nЭто чувство утраты, захлёстывающий вал эмоций, который вы переживаете, похоже на ПТСР. Посттравматическое стрессовое расстройство — распространённое состояние у многих бывших военных, переживших тяжёлую травму на войне. Хорошая новость: при консультировании симптомы ПТСР поддаются лечению. Как насчёт индивидуальных сеансов бесплатно? Взамен я хотела бы опубликовать вашу историю (анонимно, разумеется) в своём блоге. О женщинах-военных говорят так редко, и я чувствую, что ваша история будет крайне ценна для других бывших военнослужащих, которые не решаются заговорить.\r'

fixes['III. THERAPY PROGRESSION\r\n \r\n<link="data_raban_apathetic"><color=#575756>The patient was initially very unresponsive and reclusive, even apathetic in therapy sessions.</color></link> Occasionally, the patient would even switch to a rather aggressive tone, when I pushed too much towards him revealing details about his experiences and emotional state. This is probably due to the difficult conditions of living in the refugee encampment for an extensive amount of time, which is very much in conflict with the patients personality valuing strong individuality.\r\n \r\n<link="data_raban_happier"><color=#575756>Around the summer of 2012, the patient went through a sudden change. He seemed to become more outgoing, happier and willing to talk more</color></link>, though was still trying to keep conversations superficial. Throughout the sessions, the patient has been opening up more and more, and I feel like we have been making tremendous progress. In addition, the patient also seemed to much more appreciated by fellow camp residents. As of writing this, I am unsure whether to attribute the change to the effects of the therapy or to external factors.\r'] = 'III. ДИНАМИКА ТЕРАПИИ\r\n \r\n<link="data_raban_apathetic"><color=#575756>Изначально пациент был крайне замкнут и отрешён, даже апатичен на сеансах терапии.</color></link> Иногда пациент переходил на довольно агрессивный тон, когда я слишком настаивала на раскрытии деталей его переживаний и эмоционального состояния. Вероятно, это связано с тяжёлыми условиями длительного проживания в лагере беженцев, что сильно противоречит характеру пациента, ценящего ярко выраженную индивидуальность.\r\n \r\n<link="data_raban_happier"><color=#575756>Примерно летом 2012 года с пациентом произошла внезапная перемена. Он стал более общительным, радостным и разговорчивым</color></link>, хотя всё ещё старался держать беседы поверхностными. На протяжении сеансов пациент раскрывался всё больше, и я чувствую, что мы добились огромного прогресса. Кроме того, пациент стал гораздо более уважаем среди жителей лагеря. На момент написания я не уверена, следует ли приписать перемену эффекту терапии или внешним факторам.\r'

fixes['seriously, since when have you been so good at HoB? \r'] = 'серьёзно, ты когда так хорошо в HoB играть научился? \r'

fixes['@PeoplesVoice Your wife should be ashamed. Marrying people who went through traumatic experiences just to keep them under observation is completely psycho. #FakeMarriage\r'] = '@PeoplesVoice Твоей жене должно быть стыдно. Выходить замуж за людей, переживших травму, чтобы держать их под наблюдением — полный психоз. #ФальшивыйБрак\r'

fixes['<link="data_ilya_liedforraban"><color=#464646>You straight up lying to make me feel better will not change this!</color></link> We are the guardians of the truth, and THE TRUTH HURTS! You had no right to publish that story. <link="data_raban_nohero"><color=#464646>I am not a hero!</color></link>\r'] = '<link="data_ilya_liedforraban"><color=#464646>То, что ты врёшь мне в лицо, чтобы мне стало легче, ничего не изменит!</color></link> Мы хранители правды, и ПРАВДА ПРИЧИНЯЕТ БОЛЬ! Ты не имел права публиковать ту историю. <link="data_raban_nohero"><color=#464646>Я не герой!</color></link>\r'

fixes['David,\r\n\r\nYour loyalty to me is beyond any limits. <link="data_raban_davidlongtime"><color=#FFFFFF>You have been with me from the start. The People\'s Voice would not nearly have become what it is had you not been there. You\'re more than a fan. You\'re a true friend.</color></link>\r\n\r\nBut it\'s all going down. And I believe now I know why: My wife Karen must have been spying on me the whole time. The recent revelation about her connections to The Party. Her family is in politics! What did I expect? Why did I leave my guard down then? How could I be so naive and believe she would love me?\r\n\r\nI\'m tired. I\'ve been writing furiously all day to this point, and look where it got me. Nowhere. Everything around me is falling apart. I have no one left. Even my followers are turning their backs on me.\r\n\r\nIt\'s over. It has to end. I want it to end.\r\n\r\nThank you. For standing with me.'] = 'Дэвид,\r\n\r\nТвоя преданность мне не знает границ. <link="data_raban_davidlongtime"><color=#FFFFFF>Ты со мной с самого начала. «Голос Народа» никогда не стал бы тем, чем стал, без тебя. Ты больше, чем поклонник. Ты настоящий друг.</color></link>\r\n\r\nНо всё рушится. И теперь я, кажется, знаю почему: моя жена Карен, должно быть, шпионила за мной всё это время. Недавнее разоблачение её связей с Партией. Её семья в политике! Чего я ожидал? Зачем я потерял бдительность? Как я мог быть так наивен и верить, что она меня любит?\r\n\r\nЯ устал. Я яростно писал весь день, и куда это меня привело. Никуда. Всё вокруг рассыпается. У меня никого не осталось. Даже мои подписчики отворачиваются от меня.\r\n\r\nВсё кончено. Это должно закончиться. Я хочу, чтобы это закончилось.\r\n\r\nСпасибо. За то, что был рядом.'

fixes['We are here to have fun and play Hand of Blood! Come join us, no matter if you are young, old, or immortal and ageless. A special welcome to all entities from other worlds.\r\n \r\nEnjoy!\r'] = 'Мы здесь, чтобы веселиться и играть в Hand of Blood! Присоединяйтесь — неважно, молоды вы, стары или бессмертны. Особый привет всем существам из других миров.\r\n \r\nНаслаждайтесь!\r'

fixes['TRIFLITH - Prime Minister cancels crisis meeting and instead visits Parges capital. Plans to lead renewal of stalled negotiations between Kassart and opposition.\r'] = 'ТРИФЛИТ — Премьер-министр отменяет кризисное совещание и посещает столицу Паргеса. Планирует возобновить застопорившиеся переговоры между Кассартом и оппозицией.\r'

fixes['Am now proceeding according to the protocol for a situation like this. <link="data_bayte_hiding"><color=#575756>Moving to secret location in order to conceal my whereabouts.</color></link>'] = 'Действую по протоколу для подобных ситуаций. <link="data_bayte_hiding"><color=#575756>Перемещаюсь в тайное место, чтобы скрыть своё местонахождение.</color></link>'

fixes['I may have lost this battle, but THE WAR IS NOT OVER. We will fight back against the traitors Kassart and Blaine, who own this manipulative government apparatus, designed to keep us under control.\r\n \r\n<link="data_raban_accuse1"><color=#464646>The government of The Nation have dragged my family into this conflict</color></link> and I will not let them get away with this. I\'m still here, and so is The People\'s Voice. and we are loud. We have a strong group of supporters, who are loyal and will help us get back on track.\r\n \r\nKnow thy self, know thy enemy. We will fight back with a completely new People\'s Voice, resonating a kind of strength never before seen. <link="data_raban_stateofwar"><color=#464646>I hereby declare WAR on the government of The Nation,</color></link> who are trying to enslave their own people by MANIPULATING THE MEDIA! DOWN WITH THE GOVERNMENT! DOWN with KASSART and BLAINE!!'] = 'Возможно, я проиграл эту битву, но ВОЙНА НЕ ОКОНЧЕНА. Мы будем сражаться с предателями Кассартом и Блейн, которым принадлежит этот манипулятивный государственный аппарат, созданный, чтобы держать нас под контролем.\r\n \r\n<link="data_raban_accuse1"><color=#464646>Правительство Нации втянуло мою семью в этот конфликт</color></link>, и я не позволю им уйти от ответа. Я всё ещё здесь, и «Голос Народа» тоже. И мы звучим громко. У нас сильная группа сторонников, верных и готовых помочь нам встать на ноги.\r\n \r\nПознай себя, познай врага. Мы нанесём ответный удар совершенно новым «Голосом Народа», звучащим с силой, которой ещё не видели. <link="data_raban_stateofwar"><color=#464646>Настоящим объявляю ВОЙНУ правительству Нации,</color></link> которое пытается поработить собственный народ, МАНИПУЛИРУЯ СМИ! ДОЛОЙ ПРАВИТЕЛЬСТВО! ДОЛОЙ КАССАРТА и БЛЕЙН!!'

fixes['Having a lovely time at #BontonCityPark! <link="data_karen_festivities"><color=#FFFDED>I organized this get-together specifically for the refugees and a National Army veteran I am counseling who courageously rejected the war and left the army.</color></link> They are getting along very well with each other. We all invite you to join and eat, talk and laugh together! #EveryoneWelcome.\r'] = 'Чудесно проводим время в #ГородскомПаркеБонтона! <link="data_karen_festivities"><color=#FFFDED>Я организовала эту встречу специально для беженцев и ветерана армии Нации, которого консультирую — он мужественно отказался от войны и покинул армию.</color></link> Они прекрасно ладят друг с другом. Приглашаем всех — поесть, поговорить и посмеяться вместе! #ВсемРады.\r'

# Apply fixes
filled = 0
for key, val in fixes.items():
    if key in batch:
        batch[key] = val
        filled += 1
    else:
        print(f"WARNING: key not found in batch!")
        print(f"  {repr(key[:80])}")

print(f"Fixed {filled}/{len(fixes)} missing translations")

# Verify all filled
empty = sum(1 for v in batch.values() if not v)
print(f"Remaining empty: {empty}/{len(batch)}")

with open('C:/Projects/OrwellRU/translated/batch_level3_01.json', 'w', encoding='utf-8') as f:
    json.dump(batch, f, ensure_ascii=False, indent=2)
print("Saved updated batch_level3_01.json")
